dependencies:
    - name: mongodb
      version: "4.8.0"
      #repository: "file://../dependency_chart/nginx"
      repository: "https://kubernetes-charts.storage.googleapis.com/"
      condition: mongodb.enabled